// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Bridge harmony",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Bridge harmony",
            targets: ["AppModule"],
            teamIdentifier: "85GYMJ45N9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Face tracking"),
                .motion(purposeString: "Motion tracking"),
                .microphone(purposeString: "Voice tracking")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/pedroesli/KeyAudioManager", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "KeyAudioManager", package: "keyaudiomanager")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)